language: php

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.6
    - php: 7.4
    - php: 8.0
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - echo 'zend.assertions=1' > $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/assert.ini

install: |
  scripts/deps "${DEPS:-highest}"

script:
  - |
    vendor/bin/phpunit --verbose
