name: Main

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php:
          - '5.6'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
        deps:
          - highest
          - lowest
        include:
          - os: ubuntu-latest
            php: '8.0'
            coverage: 1
          - os: ubuntu-latest
            php: '7.4'
            coverage: 1
          - os: ubuntu-latest
            php: '7.3'
            phpstan: 1
          - os: ubuntu-latest
            php: '5.6'
            coverage: 1
      fail-fast: true
    name: PHP ${{ matrix.php }} / ${{ matrix.deps }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@a83d4379b1200b3d0d19ad4fe0d7a440e00749c1
        with:
          php-version: ${{ matrix.php }}
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Enable assertions
        run: echo 'zend.assertions=1' | sudo tee /etc/php/${{ matrix.php }}/cli/conf.d/assert.ini >/dev/null
      - name: Install dependencies
        run: |
          sudo phpdismod xdebug

          export WITH_PHP="${{ matrix.php }}"
          export WITH_PHPSTAN="${{ matrix.phpstan }}"

          scripts/deps "${{ matrix.deps }}"
      - name: PHPUnit
        run: |
          vendor/bin/phpunit --version | head -n1 >&2

          if [ "${{ matrix.coverage }}" = "1" ]; then
            sudo phpenmod xdebug
            vendor/bin/phpunit --verbose $args --coverage-clover=coverage.clover --coverage-text
            sudo phpdismod xdebug
          else
            vendor/bin/phpunit --verbose $args
          fi
      - name: PHPStan
        if: matrix.phpstan == 1
        run: |
          if [ -f vendor/bin/cs2pr ]; then
            (vendor/bin/phpstan analyse -c .phpstan.neon --no-progress --error-format=checkstyle || true) | vendor/bin/cs2pr
          else
            vendor/bin/phpstan analyse -c .phpstan.neon --no-progress
          fi
